# ============================================================
# AUTO-GENERATED — DO NOT EDIT BY HAND
# Run `python codegen/generate.py` to regenerate.
# Spec version: 1.112.0
# Generated at: 2026-02-24T13:41:23Z
# ============================================================

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class Endpoint:
    """Metadata for a single Teamleader Focus API operation."""

    operation_id: str
    method: str
    path: str
    tag: str
    required_params: tuple[str, ...]
    optional_params: tuple[str, ...]
    description: str = ""


# fmt: off
ENDPOINTS: dict[str, Endpoint] = {

    'accounts.projects-v2-status': Endpoint(
        operation_id='accounts.projects-v2-status',
        method='POST',
        path='/accounts.projects-v2-status',
        tag='accounts',
        required_params=(),
        optional_params=(),
        description='Fetch which version of Projects the account is using.',
    ),
    'activityTypes.list': Endpoint(
        operation_id='activityTypes.list',
        method='POST',
        path='/activityTypes.list',
        tag='activity_types',
        required_params=(),
        optional_params=('filter', 'page'),
        description='Get a list of all activity types.',
    ),
    'bookkeepingSubmissions.list': Endpoint(
        operation_id='bookkeepingSubmissions.list',
        method='POST',
        path='/bookkeepingSubmissions.list',
        tag='bookkeeping_submissions',
        required_params=(),
        optional_params=('filter',),
        description='List all bookkeeping submissions belonging to a specific financial document id and type',
    ),
    'businessTypes.list': Endpoint(
        operation_id='businessTypes.list',
        method='POST',
        path='/businessTypes.list',
        tag='business_types',
        required_params=(),
        optional_params=('country',),
        description='Get the names of business types (legal structures) a company can have within a certain country, sorted alphabetically.',
    ),
    'callOutcomes.list': Endpoint(
        operation_id='callOutcomes.list',
        method='POST',
        path='/callOutcomes.list',
        tag='call_outcomes',
        required_params=(),
        optional_params=('page',),
        description='Get a list of call outcomes.',
    ),
    'calls.add': Endpoint(
        operation_id='calls.add',
        method='POST',
        path='/calls.add',
        tag='calls',
        required_params=('assignee', 'due_at', 'participant'),
        optional_params=('custom_fields', 'deal_id', 'description'),
        description='Add a new call.',
    ),
    'calls.complete': Endpoint(
        operation_id='calls.complete',
        method='POST',
        path='/calls.complete',
        tag='calls',
        required_params=('id',),
        optional_params=('call_outcome_id', 'outcome_summary'),
        description='Mark a call as complete.',
    ),
    'calls.info': Endpoint(
        operation_id='calls.info',
        method='POST',
        path='/calls.info',
        tag='calls',
        required_params=('id',),
        optional_params=(),
        description='Get information about a call.',
    ),
    'calls.list': Endpoint(
        operation_id='calls.list',
        method='POST',
        path='/calls.list',
        tag='calls',
        required_params=(),
        optional_params=('filter', 'page'),
        description='Get a list of calls.',
    ),
    'calls.update': Endpoint(
        operation_id='calls.update',
        method='POST',
        path='/calls.update',
        tag='calls',
        required_params=('id',),
        optional_params=('assignee', 'custom_fields', 'deal_id', 'description', 'due_at', 'participant'),
        description='Update a new call.',
    ),
    'closingDays.add': Endpoint(
        operation_id='closingDays.add',
        method='POST',
        path='/closingDays.add',
        tag='closing_days',
        required_params=('day',),
        optional_params=(),
        description='Adds a closing day for the account.',
    ),
    'closingDays.delete': Endpoint(
        operation_id='closingDays.delete',
        method='POST',
        path='/closingDays.delete',
        tag='closing_days',
        required_params=('id',),
        optional_params=(),
        description='Removes a closing day for the account.',
    ),
    'closingDays.list': Endpoint(
        operation_id='closingDays.list',
        method='POST',
        path='/closingDays.list',
        tag='closing_days',
        required_params=(),
        optional_params=('filter', 'page'),
        description='Returns information about closing days of the account',
    ),
    'cloudPlatforms.url': Endpoint(
        operation_id='cloudPlatforms.url',
        method='POST',
        path='/cloudPlatforms.url',
        tag='cloud_platforms',
        required_params=('id', 'type'),
        optional_params=(),
        description='Fetch cloudPlatform url for type and id.',
    ),
    'commercialDiscounts.list': Endpoint(
        operation_id='commercialDiscounts.list',
        method='POST',
        path='/commercialDiscounts.list',
        tag='commercial_discounts',
        required_params=(),
        optional_params=('filter',),
        description='Get a list of commercial discounts.',
    ),
    'companies.add': Endpoint(
        operation_id='companies.add',
        method='POST',
        path='/companies.add',
        tag='companies',
        required_params=('name',),
        optional_params=('addresses', 'bic', 'business_type_id', 'custom_fields', 'emails', 'iban', 'language', 'marketing_mails_consent', 'national_identification_number', 'preferred_currency', 'remarks', 'responsible_user_id', 'tags', 'telephones', 'vat_number', 'website'),
        description='Add a new company.',
    ),
    'companies.delete': Endpoint(
        operation_id='companies.delete',
        method='POST',
        path='/companies.delete',
        tag='companies',
        required_params=('id',),
        optional_params=(),
        description='Delete a company.',
    ),
    'companies.info': Endpoint(
        operation_id='companies.info',
        method='POST',
        path='/companies.info',
        tag='companies',
        required_params=('id',),
        optional_params=('includes',),
        description='Get details for a single company.',
    ),
    'companies.list': Endpoint(
        operation_id='companies.list',
        method='POST',
        path='/companies.list',
        tag='companies',
        required_params=(),
        optional_params=('filter', 'includes', 'page', 'sort'),
        description='Get a list of companies.',
    ),
    'companies.tag': Endpoint(
        operation_id='companies.tag',
        method='POST',
        path='/companies.tag',
        tag='companies',
        required_params=('id', 'tags'),
        optional_params=(),
        description='Add a new or existing tag to a company.',
    ),
    'companies.untag': Endpoint(
        operation_id='companies.untag',
        method='POST',
        path='/companies.untag',
        tag='companies',
        required_params=('id', 'tags'),
        optional_params=(),
        description='Remove a tag from a company.',
    ),
    'companies.update': Endpoint(
        operation_id='companies.update',
        method='POST',
        path='/companies.update',
        tag='companies',
        required_params=('id',),
        optional_params=('addresses', 'bic', 'business_type_id', 'custom_fields', 'emails', 'iban', 'language', 'marketing_mails_consent', 'name', 'national_identification_number', 'preferred_currency', 'remarks', 'responsible_user_id', 'tags', 'telephones', 'vat_number', 'website'),
        description='Update a company.',
    ),
    'companies.uploadLogo': Endpoint(
        operation_id='companies.uploadLogo',
        method='POST',
        path='/companies.uploadLogo',
        tag='companies',
        required_params=('id', 'image'),
        optional_params=(),
        description='Update the logo of a company.',
    ),
    'contacts.add': Endpoint(
        operation_id='contacts.add',
        method='POST',
        path='/contacts.add',
        tag='contacts',
        required_params=('last_name',),
        optional_params=('addresses', 'bic', 'birthdate', 'custom_fields', 'emails', 'first_name', 'gender', 'iban', 'language', 'marketing_mails_consent', 'national_identification_number', 'remarks', 'salutation', 'tags', 'telephones', 'website'),
        description='Add a new contact.',
    ),
    'contacts.delete': Endpoint(
        operation_id='contacts.delete',
        method='POST',
        path='/contacts.delete',
        tag='contacts',
        required_params=('id',),
        optional_params=(),
        description='Delete a contact.',
    ),
    'contacts.info': Endpoint(
        operation_id='contacts.info',
        method='POST',
        path='/contacts.info',
        tag='contacts',
        required_params=('id',),
        optional_params=(),
        description='Get details for a single contact.',
    ),
    'contacts.linkToCompany': Endpoint(
        operation_id='contacts.linkToCompany',
        method='POST',
        path='/contacts.linkToCompany',
        tag='contacts',
        required_params=('company_id', 'id'),
        optional_params=('decision_maker', 'position'),
        description='Link a contact to a company.',
    ),
    'contacts.list': Endpoint(
        operation_id='contacts.list',
        method='POST',
        path='/contacts.list',
        tag='contacts',
        required_params=(),
        optional_params=('filter', 'includes', 'page', 'sort'),
        description='Get a list of contacts.',
    ),
    'contacts.tag': Endpoint(
        operation_id='contacts.tag',
        method='POST',
        path='/contacts.tag',
        tag='contacts',
        required_params=('id', 'tags'),
        optional_params=(),
        description='Add a new or existing tag to a contact.',
    ),
    'contacts.unlinkFromCompany': Endpoint(
        operation_id='contacts.unlinkFromCompany',
        method='POST',
        path='/contacts.unlinkFromCompany',
        tag='contacts',
        required_params=('company_id', 'id'),
        optional_params=(),
        description='Unlink a contact from a company.',
    ),
    'contacts.untag': Endpoint(
        operation_id='contacts.untag',
        method='POST',
        path='/contacts.untag',
        tag='contacts',
        required_params=('id', 'tags'),
        optional_params=(),
        description='Remove a tag from a contact.',
    ),
    'contacts.update': Endpoint(
        operation_id='contacts.update',
        method='POST',
        path='/contacts.update',
        tag='contacts',
        required_params=('id',),
        optional_params=('addresses', 'bic', 'birthdate', 'custom_fields', 'emails', 'first_name', 'gender', 'iban', 'language', 'last_name', 'marketing_mails_consent', 'national_identification_number', 'remarks', 'salutation', 'tags', 'telephones', 'website'),
        description='Update a contact.',
    ),
    'contacts.updateCompanyLink': Endpoint(
        operation_id='contacts.updateCompanyLink',
        method='POST',
        path='/contacts.updateCompanyLink',
        tag='contacts',
        required_params=('company_id', 'id'),
        optional_params=('decision_maker', 'position'),
        description='Update contact to company link.',
    ),
    'contacts.uploadAvatar': Endpoint(
        operation_id='contacts.uploadAvatar',
        method='POST',
        path='/contacts.uploadAvatar',
        tag='contacts',
        required_params=('id', 'image'),
        optional_params=(),
        description='Update the avatar of a contact.',
    ),
    'creditNotes.download': Endpoint(
        operation_id='creditNotes.download',
        method='POST',
        path='/creditNotes.download',
        tag='credit_notes',
        required_params=('format', 'id'),
        optional_params=(),
        description='Download a credit note in a specific format.',
    ),
    'creditNotes.info': Endpoint(
        operation_id='creditNotes.info',
        method='POST',
        path='/creditNotes.info',
        tag='credit_notes',
        required_params=('id',),
        optional_params=(),
        description='Get details for a single credit note',
    ),
    'creditNotes.list': Endpoint(
        operation_id='creditNotes.list',
        method='POST',
        path='/creditNotes.list',
        tag='credit_notes',
        required_params=(),
        optional_params=('filter', 'page'),
        description='List credit notes.',
    ),
    'creditNotes.sendViaPeppol': Endpoint(
        operation_id='creditNotes.sendViaPeppol',
        method='POST',
        path='/creditNotes.sendViaPeppol',
        tag='credit_notes',
        required_params=('id',),
        optional_params=(),
        description='Send a credit note via the Peppol network.',
    ),
    'currencies.exchangeRates': Endpoint(
        operation_id='currencies.exchangeRates',
        method='POST',
        path='/currencies.exchangeRates',
        tag='currencies',
        required_params=('base',),
        optional_params=(),
        description='Get a list of exchange rates for a provided currency.',
    ),
    'customFieldDefinitions.create': Endpoint(
        operation_id='customFieldDefinitions.create',
        method='POST',
        path='/customFieldDefinitions.create',
        tag='custom_fields',
        required_params=('context', 'label', 'type'),
        optional_params=('configuration',),
        description='Create a custom field definition.\n\n***Required scopes:*** `settings`',
    ),
    'customFieldDefinitions.info': Endpoint(
        operation_id='customFieldDefinitions.info',
        method='POST',
        path='/customFieldDefinitions.info',
        tag='custom_fields',
        required_params=('id',),
        optional_params=(),
        description='Get info about a specific custom field definition.',
    ),
    'customFieldDefinitions.list': Endpoint(
        operation_id='customFieldDefinitions.list',
        method='POST',
        path='/customFieldDefinitions.list',
        tag='custom_fields',
        required_params=(),
        optional_params=('filter', 'page', 'sort'),
        description='Get a list of all the definitions of custom fields.',
    ),
    'dayOffTypes.create': Endpoint(
        operation_id='dayOffTypes.create',
        method='POST',
        path='/dayOffTypes.create',
        tag='day_off_types',
        required_params=('name',),
        optional_params=('color', 'date_validity'),
        description='Create a new day off type.',
    ),
    'dayOffTypes.delete': Endpoint(
        operation_id='dayOffTypes.delete',
        method='POST',
        path='/dayOffTypes.delete',
        tag='day_off_types',
        required_params=('id',),
        optional_params=(),
        description='Delete a day off type.',
    ),
    'dayOffTypes.list': Endpoint(
        operation_id='dayOffTypes.list',
        method='POST',
        path='/dayOffTypes.list',
        tag='day_off_types',
        required_params=(),
        optional_params=(),
        description='Returns a list of day off types for the account',
    ),
    'dayOffTypes.update': Endpoint(
        operation_id='dayOffTypes.update',
        method='POST',
        path='/dayOffTypes.update',
        tag='day_off_types',
        required_params=('id',),
        optional_params=('color', 'date_validity', 'name'),
        description='Update a day off type.',
    ),
    'daysOff.bulkDelete': Endpoint(
        operation_id='daysOff.bulkDelete',
        method='POST',
        path='/daysOff.bulkDelete',
        tag='days_off',
        required_params=('user_id',),
        optional_params=('ids',),
        description='Deletes a list of days off for the given user.',
    ),
    'daysOff.import': Endpoint(
        operation_id='daysOff.import',
        method='POST',
        path='/daysOff.import',
        tag='days_off',
        required_params=('days', 'leave_type_id', 'user_id'),
        optional_params=(),
        description='Imports a list of days off for the given user.',
    ),
    'dealPhases.create': Endpoint(
        operation_id='dealPhases.create',
        method='POST',
        path='/dealPhases.create',
        tag='deal_phases',
        required_params=('deal_pipeline_id', 'name', 'requires_attention_after'),
        optional_params=('estimated_probability', 'follow_up_actions'),
        description='Create a new deal phase.',
    ),
    'dealPhases.delete': Endpoint(
        operation_id='dealPhases.delete',
        method='POST',
        path='/dealPhases.delete',
        tag='deal_phases',
        required_params=('id',),
        optional_params=('new_phase_id',),
        description='Delete a phase.',
    ),
    'dealPhases.duplicate': Endpoint(
        operation_id='dealPhases.duplicate',
        method='POST',
        path='/dealPhases.duplicate',
        tag='deal_phases',
        required_params=('id',),
        optional_params=(),
        description='Create a new deal phase by duplicating an existing one.',
    ),
    'dealPhases.list': Endpoint(
        operation_id='dealPhases.list',
        method='POST',
        path='/dealPhases.list',
        tag='deal_phases',
        required_params=(),
        optional_params=('filter', 'page'),
        description='Get a list of all phases a deal can go through, sorted by their order in the flow.',
    ),
    'dealPhases.move': Endpoint(
        operation_id='dealPhases.move',
        method='POST',
        path='/dealPhases.move',
        tag='deal_phases',
        required_params=('after_phase_id', 'id'),
        optional_params=(),
        description='Move a phase to a new position in the pipeline.',
    ),
    'dealPhases.update': Endpoint(
        operation_id='dealPhases.update',
        method='POST',
        path='/dealPhases.update',
        tag='deal_phases',
        required_params=('id', 'requires_attention_after'),
        optional_params=('estimated_probability', 'follow_up_actions', 'name'),
        description='Update a deal phase.',
    ),
    'dealPipelines.create': Endpoint(
        operation_id='dealPipelines.create',
        method='POST',
        path='/dealPipelines.create',
        tag='deal_pipelines',
        required_params=('name',),
        optional_params=(),
        description='Create a new deal pipeline.',
    ),
    'dealPipelines.delete': Endpoint(
        operation_id='dealPipelines.delete',
        method='POST',
        path='/dealPipelines.delete',
        tag='deal_pipelines',
        required_params=('id',),
        optional_params=('migrate_phases',),
        description='Delete a deal pipeline.',
    ),
    'dealPipelines.duplicate': Endpoint(
        operation_id='dealPipelines.duplicate',
        method='POST',
        path='/dealPipelines.duplicate',
        tag='deal_pipelines',
        required_params=('id',),
        optional_params=(),
        description='Create a new deal pipeline by duplicating an existing one.',
    ),
    'dealPipelines.list': Endpoint(
        operation_id='dealPipelines.list',
        method='POST',
        path='/dealPipelines.list',
        tag='deal_pipelines',
        required_params=(),
        optional_params=('filter', 'page'),
        description='Get a list of all deal pipelines.',
    ),
    'dealPipelines.markAsDefault': Endpoint(
        operation_id='dealPipelines.markAsDefault',
        method='POST',
        path='/dealPipelines.markAsDefault',
        tag='deal_pipelines',
        required_params=('id',),
        optional_params=(),
        description='Mark a pipeline as default.',
    ),
    'dealPipelines.update': Endpoint(
        operation_id='dealPipelines.update',
        method='POST',
        path='/dealPipelines.update',
        tag='deal_pipelines',
        required_params=('id', 'name'),
        optional_params=(),
        description='Update a single deal pipeline.',
    ),
    'dealSources.list': Endpoint(
        operation_id='dealSources.list',
        method='POST',
        path='/dealSources.list',
        tag='deal_sources',
        required_params=(),
        optional_params=('filter', 'page', 'sort'),
        description='Get a list of all deal sources, sorted alphabetically (on name).',
    ),
    'deals.create': Endpoint(
        operation_id='deals.create',
        method='POST',
        path='/deals.create',
        tag='deals',
        required_params=('lead', 'title'),
        optional_params=('currency', 'custom_fields', 'department_id', 'estimated_closing_date', 'estimated_probability', 'estimated_value', 'phase_id', 'responsible_user_id', 'source_id', 'summary'),
        description='Create a new deal for a customer.',
    ),
    'deals.delete': Endpoint(
        operation_id='deals.delete',
        method='POST',
        path='/deals.delete',
        tag='deals',
        required_params=('id',),
        optional_params=(),
        description='Delete a deal.',
    ),
    'deals.info': Endpoint(
        operation_id='deals.info',
        method='POST',
        path='/deals.info',
        tag='deals',
        required_params=('id',),
        optional_params=(),
        description='Get details for a single deal.',
    ),
    'deals.list': Endpoint(
        operation_id='deals.list',
        method='POST',
        path='/deals.list',
        tag='deals',
        required_params=(),
        optional_params=('filter', 'includes', 'page', 'sort'),
        description='Get a list of deals.',
    ),
    'deals.lose': Endpoint(
        operation_id='deals.lose',
        method='POST',
        path='/deals.lose',
        tag='deals',
        required_params=('id',),
        optional_params=('extra_info', 'reason_id'),
        description='Mark a deal as lost.',
    ),
    'deals.move': Endpoint(
        operation_id='deals.move',
        method='POST',
        path='/deals.move',
        tag='deals',
        required_params=('id', 'phase_id'),
        optional_params=(),
        description='Move the deal to a different phase.',
    ),
    'deals.update': Endpoint(
        operation_id='deals.update',
        method='POST',
        path='/deals.update',
        tag='deals',
        required_params=('id',),
        optional_params=('currency', 'custom_fields', 'department_id', 'estimated_closing_date', 'estimated_probability', 'estimated_value', 'lead', 'responsible_user_id', 'source_id', 'summary', 'title'),
        description='Update a deal.',
    ),
    'deals.win': Endpoint(
        operation_id='deals.win',
        method='POST',
        path='/deals.win',
        tag='deals',
        required_params=('id',),
        optional_params=(),
        description='Mark a deal as won.',
    ),
    'departments.info': Endpoint(
        operation_id='departments.info',
        method='POST',
        path='/departments.info',
        tag='departments',
        required_params=('id',),
        optional_params=(),
        description='Get details for a single department.',
    ),
    'departments.list': Endpoint(
        operation_id='departments.list',
        method='POST',
        path='/departments.list',
        tag='departments',
        required_params=(),
        optional_params=('filter', 'sort'),
        description='Get a list of departments.',
    ),
    'documentTemplates.list': Endpoint(
        operation_id='documentTemplates.list',
        method='POST',
        path='/documentTemplates.list',
        tag='document_templates',
        required_params=(),
        optional_params=(),
        description='Get a list of all document templates.',
    ),
    'emailTracking.create': Endpoint(
        operation_id='emailTracking.create',
        method='POST',
        path='/emailTracking.create',
        tag='email_tracking',
        required_params=('content', 'subject'),
        optional_params=('attachments', 'title'),
        description='Create a new email tracking.',
    ),
    'emailTracking.list': Endpoint(
        operation_id='emailTracking.list',
        method='POST',
        path='/emailTracking.list',
        tag='email_tracking',
        required_params=(),
        optional_params=(),
        description='Get a list of all email tracking.',
    ),
    'events.cancel': Endpoint(
        operation_id='events.cancel',
        method='POST',
        path='/events.cancel',
        tag='calendar_events',
        required_params=('id',),
        optional_params=(),
        description='Cancel a calendar event (for all attendees).',
    ),
    'events.create': Endpoint(
        operation_id='events.create',
        method='POST',
        path='/events.create',
        tag='calendar_events',
        required_params=('activity_type_id', 'ends_at', 'starts_at', 'title'),
        optional_params=('attendees', 'description', 'links', 'location', 'work_type_id'),
        description='Create a new calendar event.',
    ),
    'events.info': Endpoint(
        operation_id='events.info',
        method='POST',
        path='/events.info',
        tag='calendar_events',
        required_params=('id',),
        optional_params=(),
        description='Get details for a single calendar event.',
    ),
    'events.list': Endpoint(
        operation_id='events.list',
        method='POST',
        path='/events.list',
        tag='calendar_events',
        required_params=(),
        optional_params=('filter', 'page', 'sort'),
        description='Get a list of calendar events.',
    ),
    'events.update': Endpoint(
        operation_id='events.update',
        method='POST',
        path='/events.update',
        tag='calendar_events',
        required_params=('id',),
        optional_params=('attendees', 'description', 'ends_at', 'links', 'location', 'starts_at', 'title', 'work_type_id'),
        description='Update a calendar event.',
    ),
    'expenses.list': Endpoint(
        operation_id='expenses.list',
        method='POST',
        path='/expenses.list',
        tag='expenses',
        required_params=(),
        optional_params=('filter', 'page', 'sort'),
        description='Get a list of all expenses.',
    ),
    'files.delete': Endpoint(
        operation_id='files.delete',
        method='POST',
        path='/files.delete',
        tag='files',
        required_params=('id',),
        optional_params=(),
        description='Delete a file.',
    ),
    'files.download': Endpoint(
        operation_id='files.download',
        method='POST',
        path='/files.download',
        tag='files',
        required_params=('id',),
        optional_params=(),
        description='Request the download link for a file.',
    ),
    'files.info': Endpoint(
        operation_id='files.info',
        method='POST',
        path='/files.info',
        tag='files',
        required_params=('id',),
        optional_params=(),
        description='Get details for a single file.',
    ),
    'files.list': Endpoint(
        operation_id='files.list',
        method='POST',
        path='/files.list',
        tag='files',
        required_params=('filter',),
        optional_params=('page', 'sort'),
        description='Get a list of files.',
    ),
    'files.upload': Endpoint(
        operation_id='files.upload',
        method='POST',
        path='/files.upload',
        tag='files',
        required_params=('name', 'subject'),
        optional_params=('folder',),
        description='Request the upload link for a file.\n\nThe following remarks apply to `temporary` files:\n- they exist for a maximum of 24 hours if not linked to an entity\n- do not show up in any file overview\n- are not included in external syncs',
    ),
    'incomingCreditNotes.add': Endpoint(
        operation_id='incomingCreditNotes.add',
        method='POST',
        path='/incomingCreditNotes.add',
        tag='incoming_credit_notes',
        required_params=('currency', 'title'),
        optional_params=('company_entity_id', 'document_number', 'due_date', 'file_id', 'iban_number', 'invoice_date', 'payment_reference', 'supplier_id', 'total'),
        description='Adds an incoming credit note.',
    ),
    'incomingCreditNotes.approve': Endpoint(
        operation_id='incomingCreditNotes.approve',
        method='POST',
        path='/incomingCreditNotes.approve',
        tag='incoming_credit_notes',
        required_params=('id',),
        optional_params=(),
        description='Approve an incoming credit note.',
    ),
    'incomingCreditNotes.delete': Endpoint(
        operation_id='incomingCreditNotes.delete',
        method='POST',
        path='/incomingCreditNotes.delete',
        tag='incoming_credit_notes',
        required_params=('id',),
        optional_params=(),
        description='Deletes an incoming credit note.',
    ),
    'incomingCreditNotes.info': Endpoint(
        operation_id='incomingCreditNotes.info',
        method='POST',
        path='/incomingCreditNotes.info',
        tag='incoming_credit_notes',
        required_params=('id',),
        optional_params=(),
        description='Get details for a single incoming credit note.',
    ),
    'incomingCreditNotes.listPayments': Endpoint(
        operation_id='incomingCreditNotes.listPayments',
        method='POST',
        path='/incomingCreditNotes.listPayments',
        tag='incoming_credit_notes',
        required_params=('id',),
        optional_params=(),
        description='List payments for an incoming credit note.',
    ),
    'incomingCreditNotes.markAsPendingReview': Endpoint(
        operation_id='incomingCreditNotes.markAsPendingReview',
        method='POST',
        path='/incomingCreditNotes.markAsPendingReview',
        tag='incoming_credit_notes',
        required_params=('id',),
        optional_params=(),
        description='Mark an incoming credit note as pending review.',
    ),
    'incomingCreditNotes.refuse': Endpoint(
        operation_id='incomingCreditNotes.refuse',
        method='POST',
        path='/incomingCreditNotes.refuse',
        tag='incoming_credit_notes',
        required_params=('id',),
        optional_params=(),
        description='Refuse an incoming credit note.',
    ),
    'incomingCreditNotes.registerPayment': Endpoint(
        operation_id='incomingCreditNotes.registerPayment',
        method='POST',
        path='/incomingCreditNotes.registerPayment',
        tag='incoming_credit_notes',
        required_params=('id', 'paid_at', 'payment'),
        optional_params=('payment_method_id', 'remark'),
        description='Register a payment for an incoming credit note.',
    ),
    'incomingCreditNotes.removePayment': Endpoint(
        operation_id='incomingCreditNotes.removePayment',
        method='POST',
        path='/incomingCreditNotes.removePayment',
        tag='incoming_credit_notes',
        required_params=('id', 'payment_id'),
        optional_params=(),
        description='Remove a payment from an incoming credit note.',
    ),
    'incomingCreditNotes.sendToBookkeeping': Endpoint(
        operation_id='incomingCreditNotes.sendToBookkeeping',
        method='POST',
        path='/incomingCreditNotes.sendToBookkeeping',
        tag='incoming_credit_notes',
        required_params=('id',),
        optional_params=(),
        description='Send an incoming credit note to bookkeeping.',
    ),
    'incomingCreditNotes.update': Endpoint(
        operation_id='incomingCreditNotes.update',
        method='POST',
        path='/incomingCreditNotes.update',
        tag='incoming_credit_notes',
        required_params=('id',),
        optional_params=('company_entity_id', 'currency', 'document_number', 'due_date', 'file_id', 'iban_number', 'invoice_date', 'payment_reference', 'supplier_id', 'title', 'total'),
        description='Updates an incoming credit note.',
    ),
    'incomingCreditNotes.updatePayment': Endpoint(
        operation_id='incomingCreditNotes.updatePayment',
        method='POST',
        path='/incomingCreditNotes.updatePayment',
        tag='incoming_credit_notes',
        required_params=('id', 'payment_id'),
        optional_params=('paid_at', 'payment', 'payment_method_id', 'remark'),
        description='Update a payment for an incoming credit note.',
    ),
    'incomingInvoices.add': Endpoint(
        operation_id='incomingInvoices.add',
        method='POST',
        path='/incomingInvoices.add',
        tag='incoming_invoices',
        required_params=('currency', 'title'),
        optional_params=('company_entity_id', 'document_number', 'due_date', 'file_id', 'iban_number', 'invoice_date', 'payment_reference', 'supplier_id', 'total'),
        description='Adds an incoming invoice.',
    ),
    'incomingInvoices.approve': Endpoint(
        operation_id='incomingInvoices.approve',
        method='POST',
        path='/incomingInvoices.approve',
        tag='incoming_invoices',
        required_params=('id',),
        optional_params=(),
        description='Approve an incoming invoice.',
    ),
    'incomingInvoices.delete': Endpoint(
        operation_id='incomingInvoices.delete',
        method='POST',
        path='/incomingInvoices.delete',
        tag='incoming_invoices',
        required_params=('id',),
        optional_params=(),
        description='Deletes an incoming invoice.',
    ),
    'incomingInvoices.info': Endpoint(
        operation_id='incomingInvoices.info',
        method='POST',
        path='/incomingInvoices.info',
        tag='incoming_invoices',
        required_params=('id',),
        optional_params=(),
        description='Get details for a single incoming invoice.',
    ),
    'incomingInvoices.listPayments': Endpoint(
        operation_id='incomingInvoices.listPayments',
        method='POST',
        path='/incomingInvoices.listPayments',
        tag='incoming_invoices',
        required_params=('id',),
        optional_params=(),
        description='List payments for an incoming invoice.',
    ),
    'incomingInvoices.markAsPendingReview': Endpoint(
        operation_id='incomingInvoices.markAsPendingReview',
        method='POST',
        path='/incomingInvoices.markAsPendingReview',
        tag='incoming_invoices',
        required_params=('id',),
        optional_params=(),
        description='Mark an incoming invoice as pending review.',
    ),
    'incomingInvoices.refuse': Endpoint(
        operation_id='incomingInvoices.refuse',
        method='POST',
        path='/incomingInvoices.refuse',
        tag='incoming_invoices',
        required_params=('id',),
        optional_params=(),
        description='Refuse an incoming invoice.',
    ),
    'incomingInvoices.registerPayment': Endpoint(
        operation_id='incomingInvoices.registerPayment',
        method='POST',
        path='/incomingInvoices.registerPayment',
        tag='incoming_invoices',
        required_params=('id', 'paid_at', 'payment'),
        optional_params=('payment_method_id', 'remark'),
        description='Register a payment for an incoming invoice.',
    ),
    'incomingInvoices.removePayment': Endpoint(
        operation_id='incomingInvoices.removePayment',
        method='POST',
        path='/incomingInvoices.removePayment',
        tag='incoming_invoices',
        required_params=('id', 'payment_id'),
        optional_params=(),
        description='Remove a payment from an incoming invoice.',
    ),
    'incomingInvoices.sendToBookkeeping': Endpoint(
        operation_id='incomingInvoices.sendToBookkeeping',
        method='POST',
        path='/incomingInvoices.sendToBookkeeping',
        tag='incoming_invoices',
        required_params=('id',),
        optional_params=(),
        description='Send an incoming invoice to bookkeeping.',
    ),
    'incomingInvoices.update': Endpoint(
        operation_id='incomingInvoices.update',
        method='POST',
        path='/incomingInvoices.update',
        tag='incoming_invoices',
        required_params=('id',),
        optional_params=('company_entity_id', 'currency', 'document_number', 'due_date', 'file_id', 'iban_number', 'invoice_date', 'payment_reference', 'supplier_id', 'title', 'total'),
        description='Updates an incoming invoice.',
    ),
    'incomingInvoices.updatePayment': Endpoint(
        operation_id='incomingInvoices.updatePayment',
        method='POST',
        path='/incomingInvoices.updatePayment',
        tag='incoming_invoices',
        required_params=('id', 'payment_id'),
        optional_params=('paid_at', 'payment', 'payment_method_id', 'remark'),
        description='Update a payment for an incoming invoice.',
    ),
    'invoices.book': Endpoint(
        operation_id='invoices.book',
        method='POST',
        path='/invoices.book',
        tag='invoices',
        required_params=('id', 'on'),
        optional_params=(),
        description='Book a draft invoice.',
    ),
    'invoices.copy': Endpoint(
        operation_id='invoices.copy',
        method='POST',
        path='/invoices.copy',
        tag='invoices',
        required_params=('id',),
        optional_params=(),
        description='Creates a new draft invoice based on another invoice.',
    ),
    'invoices.credit': Endpoint(
        operation_id='invoices.credit',
        method='POST',
        path='/invoices.credit',
        tag='invoices',
        required_params=('id',),
        optional_params=('credit_note_date',),
        description='Credit an invoice completely.',
    ),
    'invoices.creditPartially': Endpoint(
        operation_id='invoices.creditPartially',
        method='POST',
        path='/invoices.creditPartially',
        tag='invoices',
        required_params=('grouped_lines', 'id'),
        optional_params=('credit_note_date', 'discounts'),
        description='Credit an invoice partially.',
    ),
    'invoices.delete': Endpoint(
        operation_id='invoices.delete',
        method='POST',
        path='/invoices.delete',
        tag='invoices',
        required_params=('id',),
        optional_params=(),
        description='Delete an existing invoice. Only possible for draft invoices or the last booked invoice.',
    ),
    'invoices.download': Endpoint(
        operation_id='invoices.download',
        method='POST',
        path='/invoices.download',
        tag='invoices',
        required_params=('format', 'id'),
        optional_params=(),
        description='Download an invoice in a specific format.',
    ),
    'invoices.draft': Endpoint(
        operation_id='invoices.draft',
        method='POST',
        path='/invoices.draft',
        tag='invoices',
        required_params=('department_id', 'grouped_lines', 'invoicee', 'payment_term'),
        optional_params=('currency', 'custom_fields', 'delivery_date', 'discounts', 'document_template_id', 'expected_payment_method', 'invoice_date', 'note', 'project_id', 'purchase_order_number'),
        description='Draft a new invoice.',
    ),
    'invoices.info': Endpoint(
        operation_id='invoices.info',
        method='POST',
        path='/invoices.info',
        tag='invoices',
        required_params=(),
        optional_params=('id', 'includes'),
        description='Get details for a single invoice.',
    ),
    'invoices.list': Endpoint(
        operation_id='invoices.list',
        method='POST',
        path='/invoices.list',
        tag='invoices',
        required_params=(),
        optional_params=('filter', 'includes', 'page', 'sort'),
        description='Get a list of invoices.',
    ),
    'invoices.registerPayment': Endpoint(
        operation_id='invoices.registerPayment',
        method='POST',
        path='/invoices.registerPayment',
        tag='invoices',
        required_params=('id', 'paid_at', 'payment'),
        optional_params=('payment_method_id',),
        description='Register a payment for an invoice.',
    ),
    'invoices.removePayments': Endpoint(
        operation_id='invoices.removePayments',
        method='POST',
        path='/invoices.removePayments',
        tag='invoices',
        required_params=('id',),
        optional_params=(),
        description='Marks an invoice as unpaid and removes all linked payments. This will also trigger a re-rendering of the invoice PDF.',
    ),
    'invoices.send': Endpoint(
        operation_id='invoices.send',
        method='POST',
        path='/invoices.send',
        tag='invoices',
        required_params=('content', 'id'),
        optional_params=('attachments', 'recipients'),
        description='Send an invoice via e-mail.',
    ),
    'invoices.sendViaPeppol': Endpoint(
        operation_id='invoices.sendViaPeppol',
        method='POST',
        path='/invoices.sendViaPeppol',
        tag='invoices',
        required_params=('id',),
        optional_params=(),
        description='Send an invoice via the Peppol network.',
    ),
    'invoices.update': Endpoint(
        operation_id='invoices.update',
        method='POST',
        path='/invoices.update',
        tag='invoices',
        required_params=('id',),
        optional_params=('currency', 'custom_fields', 'delivery_date', 'discounts', 'document_template_id', 'expected_payment_method', 'grouped_lines', 'invoice_date', 'invoicee', 'note', 'payment_term', 'project_id', 'purchase_order_number'),
        description='Update a draft invoice. Booked invoices cannot be updated.',
    ),
    'invoices.updateBooked': Endpoint(
        operation_id='invoices.updateBooked',
        method='POST',
        path='/invoices.updateBooked',
        tag='invoices',
        required_params=('id',),
        optional_params=('custom_fields', 'grouped_lines', 'invoice_date', 'invoicee', 'note', 'payment_term', 'project_id'),
        description='Update a booked invoice. Only available when editing booked invoices is allowed through the settings.',
    ),
    'levelTwoAreas.list': Endpoint(
        operation_id='levelTwoAreas.list',
        method='POST',
        path='/levelTwoAreas.list',
        tag='addresses',
        required_params=('country',),
        optional_params=('language',),
        description='Get a list of level two areas (which correspond to provinces, departments or states in most countries).',
    ),
    'lostReasons.list': Endpoint(
        operation_id='lostReasons.list',
        method='POST',
        path='/lostReasons.list',
        tag='deals',
        required_params=(),
        optional_params=('filter', 'page', 'sort'),
        description='Get a list of lost reasons for deals.',
    ),
    'mailTemplates.list': Endpoint(
        operation_id='mailTemplates.list',
        method='POST',
        path='/mailTemplates.list',
        tag='mail_templates',
        required_params=(),
        optional_params=(),
        description='Get a list of all mail templates.',
    ),
    'meetings.complete': Endpoint(
        operation_id='meetings.complete',
        method='POST',
        path='/meetings.complete',
        tag='meetings',
        required_params=('id',),
        optional_params=(),
        description='Mark a meeting as complete.',
    ),
    'meetings.createReport': Endpoint(
        operation_id='meetings.createReport',
        method='POST',
        path='/meetings.createReport',
        tag='meetings',
        required_params=('attach_to', 'id'),
        optional_params=('custom_fields', 'summary'),
        description='Creates a report for a meeting.',
    ),
    'meetings.delete': Endpoint(
        operation_id='meetings.delete',
        method='POST',
        path='/meetings.delete',
        tag='meetings',
        required_params=('id',),
        optional_params=(),
        description='Deletes a meeting.',
    ),
    'meetings.info': Endpoint(
        operation_id='meetings.info',
        method='POST',
        path='/meetings.info',
        tag='meetings',
        required_params=('id',),
        optional_params=('includes',),
        description='Get information about a meeting.',
    ),
    'meetings.list': Endpoint(
        operation_id='meetings.list',
        method='POST',
        path='/meetings.list',
        tag='meetings',
        required_params=(),
        optional_params=('filter', 'includes', 'page', 'sort'),
        description='Get a list of meetings.',
    ),
    'meetings.schedule': Endpoint(
        operation_id='meetings.schedule',
        method='POST',
        path='/meetings.schedule',
        tag='meetings',
        required_params=('attendees', 'ends_at', 'starts_at', 'title'),
        optional_params=('custom_fields', 'customer', 'deal_id', 'description', 'location', 'milestone_id', 'work_order_id'),
        description='Schedule a meeting.',
    ),
    'meetings.update': Endpoint(
        operation_id='meetings.update',
        method='POST',
        path='/meetings.update',
        tag='meetings',
        required_params=('id',),
        optional_params=('attendees', 'custom_fields', 'customer', 'deal_id', 'description', 'ends_at', 'location', 'milestone_id', 'starts_at', 'title'),
        description='Update a meeting.',
    ),
    'migrate.activityType': Endpoint(
        operation_id='migrate.activityType',
        method='POST',
        path='/migrate.activityType',
        tag='migrating',
        required_params=(),
        optional_params=('type',),
        description='Translates `meeting`, `call` and `task` into their respective activity type UUID.',
    ),
    'migrate.id': Endpoint(
        operation_id='migrate.id',
        method='POST',
        path='/migrate.id',
        tag='migrating',
        required_params=(),
        optional_params=('id', 'type'),
        description='Translates an ID from the deprecated API into a new UUID.',
    ),
    'migrate.taxRate': Endpoint(
        operation_id='migrate.taxRate',
        method='POST',
        path='/migrate.taxRate',
        tag='migrating',
        required_params=(),
        optional_params=('department_id', 'tax_rate'),
        description='Translates tax rates from the deprecated API into a new UUID tax rate.',
    ),
    'LegacyMilestones.close': Endpoint(
        operation_id='LegacyMilestones.close',
        method='POST',
        path='/milestones.close',
        tag='legacy_milestones',
        required_params=('id',),
        optional_params=(),
        description='Close a milestone. All open tasks will be closed, open meetings will remain open. Closing the last open milestone will also close the project.',
    ),
    'LegacyMilestones.create': Endpoint(
        operation_id='LegacyMilestones.create',
        method='POST',
        path='/milestones.create',
        tag='legacy_milestones',
        required_params=('due_on', 'name', 'project_id', 'responsible_user_id'),
        optional_params=('custom_fields', 'depends_on', 'description', 'starts_on'),
        description='Create a new milestone.',
    ),
    'LegacyMilestones.delete': Endpoint(
        operation_id='LegacyMilestones.delete',
        method='POST',
        path='/milestones.delete',
        tag='legacy_milestones',
        required_params=('id',),
        optional_params=(),
        description='Delete a milestone.',
    ),
    'LegacyMilestones.info': Endpoint(
        operation_id='LegacyMilestones.info',
        method='POST',
        path='/milestones.info',
        tag='legacy_milestones',
        required_params=('id',),
        optional_params=(),
        description='Get details for a single milestone.',
    ),
    'LegacyMilestones.list': Endpoint(
        operation_id='LegacyMilestones.list',
        method='POST',
        path='/milestones.list',
        tag='legacy_milestones',
        required_params=(),
        optional_params=('filter', 'page', 'sort'),
        description='Get a list of project milestones.',
    ),
    'LegacyMilestones.open': Endpoint(
        operation_id='LegacyMilestones.open',
        method='POST',
        path='/milestones.open',
        tag='legacy_milestones',
        required_params=('id',),
        optional_params=(),
        description="(Re)open a milestone. If the milestone's project is closed, the project will be reopened.",
    ),
    'LegacyMilestones.update': Endpoint(
        operation_id='LegacyMilestones.update',
        method='POST',
        path='/milestones.update',
        tag='legacy_milestones',
        required_params=('id',),
        optional_params=('custom_fields', 'depends_on', 'description', 'due_on', 'name', 'propagate_date_changes', 'responsible_user_id', 'starts_on'),
        description='Update a milestone.',
    ),
    'notes.create': Endpoint(
        operation_id='notes.create',
        method='POST',
        path='/notes.create',
        tag='notes',
        required_params=('content', 'subject'),
        optional_params=('notify',),
        description='Create a new note.',
    ),
    'notes.list': Endpoint(
        operation_id='notes.list',
        method='POST',
        path='/notes.list',
        tag='notes',
        required_params=(),
        optional_params=(),
        description='Get a list of all notes.',
    ),
    'notes.update': Endpoint(
        operation_id='notes.update',
        method='POST',
        path='/notes.update',
        tag='notes',
        required_params=('id',),
        optional_params=('content',),
        description='Update an existing note.',
    ),
    'orders.info': Endpoint(
        operation_id='orders.info',
        method='POST',
        path='/orders.info',
        tag='orders',
        required_params=('id',),
        optional_params=('includes',),
        description='Get details for a single order.',
    ),
    'orders.list': Endpoint(
        operation_id='orders.list',
        method='POST',
        path='/orders.list',
        tag='orders',
        required_params=(),
        optional_params=('filter', 'includes'),
        description='Get a list of orders.',
    ),
    'paymentMethods.list': Endpoint(
        operation_id='paymentMethods.list',
        method='POST',
        path='/paymentMethods.list',
        tag='payment_methods',
        required_params=(),
        optional_params=('filter', 'page'),
        description='Get a list of payment methods.',
    ),
    'paymentTerms.list': Endpoint(
        operation_id='paymentTerms.list',
        method='POST',
        path='/paymentTerms.list',
        tag='payment_terms',
        required_params=(),
        optional_params=(),
        description='Get a list of available payment terms.',
    ),
    'plannableItems.info': Endpoint(
        operation_id='plannableItems.info',
        method='POST',
        path='/plannableItems.info',
        tag='plannable_items',
        required_params=(),
        optional_params=('id', 'source'),
        description='Returns the info for a single plannable item, either by ID or source if the ID is unknown.',
    ),
    'plannableItems.list': Endpoint(
        operation_id='plannableItems.list',
        method='POST',
        path='/plannableItems.list',
        tag='plannable_items',
        required_params=(),
        optional_params=('filter', 'page', 'sort'),
        description='Lists all plannable items that match the optional filters provided.',
    ),
    'priceLists.list': Endpoint(
        operation_id='priceLists.list',
        method='POST',
        path='/priceLists.list',
        tag='price_lists',
        required_params=(),
        optional_params=('filter',),
        description='Get a list of priceLists.',
    ),
    'productCategories.list': Endpoint(
        operation_id='productCategories.list',
        method='POST',
        path='/productCategories.list',
        tag='product_categories',
        required_params=(),
        optional_params=('filter',),
        description='Get a list of product categories.',
    ),
    'products.add': Endpoint(
        operation_id='products.add',
        method='POST',
        path='/products.add',
        tag='products',
        required_params=(),
        optional_params=(),
        description='Add a new product.',
    ),
    'products.delete': Endpoint(
        operation_id='products.delete',
        method='POST',
        path='/products.delete',
        tag='products',
        required_params=('id',),
        optional_params=(),
        description='Delete a product.',
    ),
    'products.info': Endpoint(
        operation_id='products.info',
        method='POST',
        path='/products.info',
        tag='products',
        required_params=('id',),
        optional_params=('includes',),
        description='Get details for a single product.',
    ),
    'products.list': Endpoint(
        operation_id='products.list',
        method='POST',
        path='/products.list',
        tag='products',
        required_params=(),
        optional_params=('filter', 'page'),
        description='Get a list of products.',
    ),
    'products.update': Endpoint(
        operation_id='products.update',
        method='POST',
        path='/products.update',
        tag='products',
        required_params=('id',),
        optional_params=('code', 'configuration', 'custom_fields', 'department_id', 'description', 'name', 'price_list_prices', 'product_category_id', 'purchase_price', 'selling_price', 'stock', 'tax_rate_id', 'unit_of_measure_id'),
        description='Update a product.',
    ),
    'NextgenProjectsExternalParties.addToProject': Endpoint(
        operation_id='NextgenProjectsExternalParties.addToProject',
        method='POST',
        path='/projects-v2/externalParties.addToProject',
        tag='external_parties',
        required_params=('customer', 'project_id'),
        optional_params=('function', 'sub_function'),
        description='Add an external party to a project.',
    ),
    'NextgenProjectsExternalParties.delete': Endpoint(
        operation_id='NextgenProjectsExternalParties.delete',
        method='POST',
        path='/projects-v2/externalParties.delete',
        tag='external_parties',
        required_params=('id',),
        optional_params=(),
        description='Delete an external party.',
    ),
    'NextgenProjectsExternalParties.update': Endpoint(
        operation_id='NextgenProjectsExternalParties.update',
        method='POST',
        path='/projects-v2/externalParties.update',
        tag='external_parties',
        required_params=('id',),
        optional_params=('customer', 'function', 'sub_function'),
        description='Update an external party.',
    ),
    'NextgenProjectsMaterials.assign': Endpoint(
        operation_id='NextgenProjectsMaterials.assign',
        method='POST',
        path='/projects-v2/materials.assign',
        tag='materials',
        required_params=('assignee', 'id'),
        optional_params=(),
        description='Assign a user or a team to a material.',
    ),
    'NextgenProjectsMaterials.create': Endpoint(
        operation_id='NextgenProjectsMaterials.create',
        method='POST',
        path='/projects-v2/materials.create',
        tag='materials',
        required_params=('project_id', 'title'),
        optional_params=('after_id', 'assignees', 'billing_method', 'description', 'end_date', 'external_budget', 'fixed_price', 'group_id', 'internal_budget', 'product_id', 'quantity', 'quantity_estimated', 'start_date', 'unit_cost', 'unit_id', 'unit_price'),
        description='Create a material. All properties except for `title` and `project_id` are optional.',
    ),
    'NextgenProjectsMaterials.delete': Endpoint(
        operation_id='NextgenProjectsMaterials.delete',
        method='POST',
        path='/projects-v2/materials.delete',
        tag='materials',
        required_params=('id',),
        optional_params=(),
        description='Delete a material.',
    ),
    'NextgenProjectsMaterials.duplicate': Endpoint(
        operation_id='NextgenProjectsMaterials.duplicate',
        method='POST',
        path='/projects-v2/materials.duplicate',
        tag='materials',
        required_params=('origin_id',),
        optional_params=(),
        description='Duplicate a material.',
    ),
    'NextgenProjectsMaterials.info': Endpoint(
        operation_id='NextgenProjectsMaterials.info',
        method='POST',
        path='/projects-v2/materials.info',
        tag='materials',
        required_params=('id',),
        optional_params=(),
        description='Returns all the information for one material.',
    ),
    'NextgenProjectsMaterials.list': Endpoint(
        operation_id='NextgenProjectsMaterials.list',
        method='POST',
        path='/projects-v2/materials.list',
        tag='materials',
        required_params=(),
        optional_params=('filter',),
        description='Lists all the materials that match the optional filters provided.',
    ),
    'NextgenProjectsMaterials.unassign': Endpoint(
        operation_id='NextgenProjectsMaterials.unassign',
        method='POST',
        path='/projects-v2/materials.unassign',
        tag='materials',
        required_params=('assignee', 'id'),
        optional_params=(),
        description='Unassign a user or a team from a material.',
    ),
    'NextgenProjectsMaterials.update': Endpoint(
        operation_id='NextgenProjectsMaterials.update',
        method='POST',
        path='/projects-v2/materials.update',
        tag='materials',
        required_params=('id',),
        optional_params=('billing_method', 'description', 'end_date', 'external_budget', 'fixed_price', 'internal_budget', 'product_id', 'quantity', 'quantity_estimated', 'start_date', 'status', 'title', 'unit_cost', 'unit_id', 'unit_price'),
        description='Update a material. All attributes except for `id` are optional. Providing `null` will clear that value from the project (for properties that are nullable).',
    ),
    'projectGroups.assign': Endpoint(
        operation_id='projectGroups.assign',
        method='POST',
        path='/projects-v2/projectGroups.assign',
        tag='groups',
        required_params=('assignee', 'id'),
        optional_params=(),
        description='Assign a user or a team to a group.',
    ),
    'projectGroups.create': Endpoint(
        operation_id='projectGroups.create',
        method='POST',
        path='/projects-v2/projectGroups.create',
        tag='groups',
        required_params=('project_id', 'title'),
        optional_params=('assignees', 'billing_method', 'color', 'description', 'end_date', 'external_budget', 'fixed_price', 'internal_budget', 'start_date'),
        description='Create a group. All properties except for `title` and `project_id` are optional.',
    ),
    'projectGroups.delete': Endpoint(
        operation_id='projectGroups.delete',
        method='POST',
        path='/projects-v2/projectGroups.delete',
        tag='groups',
        required_params=('delete_strategy', 'id'),
        optional_params=(),
        description='Delete a group.',
    ),
    'projectGroups.duplicate': Endpoint(
        operation_id='projectGroups.duplicate',
        method='POST',
        path='/projects-v2/projectGroups.duplicate',
        tag='groups',
        required_params=('origin_id',),
        optional_params=(),
        description='Duplicate a group and its entities, without any time trackings.',
    ),
    'projectGroups.info': Endpoint(
        operation_id='projectGroups.info',
        method='POST',
        path='/projects-v2/projectGroups.info',
        tag='groups',
        required_params=('id',),
        optional_params=(),
        description='Returns all the information for one group.',
    ),
    'projectGroups.list': Endpoint(
        operation_id='projectGroups.list',
        method='POST',
        path='/projects-v2/projectGroups.list',
        tag='groups',
        required_params=(),
        optional_params=('filter',),
        description='Lists all the groups that match the optional filters provided.',
    ),
    'projectGroups.unassign': Endpoint(
        operation_id='projectGroups.unassign',
        method='POST',
        path='/projects-v2/projectGroups.unassign',
        tag='groups',
        required_params=('assignee', 'id'),
        optional_params=(),
        description='Unassign a user or a team from a group.',
    ),
    'projectGroups.update': Endpoint(
        operation_id='projectGroups.update',
        method='POST',
        path='/projects-v2/projectGroups.update',
        tag='groups',
        required_params=('id',),
        optional_params=('billing_method', 'color', 'description', 'end_date', 'external_budget', 'fixed_price', 'internal_budget', 'start_date', 'title'),
        description='Update a group. All attributes except for `id` are optional. Providing `null` will clear that value from the project (for properties that are nullable).',
    ),
    'projectLines.addToGroup': Endpoint(
        operation_id='projectLines.addToGroup',
        method='POST',
        path='/projects-v2/projectLines.addToGroup',
        tag='project_lines',
        required_params=('group_id', 'line_id'),
        optional_params=(),
        description='Add an existing task or material to a group.',
    ),
    'projectLines.list': Endpoint(
        operation_id='projectLines.list',
        method='POST',
        path='/projects-v2/projectLines.list',
        tag='project_lines',
        required_params=('project_id',),
        optional_params=('filter',),
        description='All line types (tasks, materials, groups) can be side-loaded.',
    ),
    'projectLines.removeFromGroup': Endpoint(
        operation_id='projectLines.removeFromGroup',
        method='POST',
        path='/projects-v2/projectLines.removeFromGroup',
        tag='project_lines',
        required_params=('line_id',),
        optional_params=(),
        description='Remove a task or material from the group it is currently in.',
    ),
    'NextgenProjects.addCustomer': Endpoint(
        operation_id='NextgenProjects.addCustomer',
        method='POST',
        path='/projects-v2/projects.addCustomer',
        tag='projects',
        required_params=('customer', 'id'),
        optional_params=(),
        description="Add a customer to the project. Doesn't fail if the customer was already added.",
    ),
    'NextgenProjects.addDeal': Endpoint(
        operation_id='NextgenProjects.addDeal',
        method='POST',
        path='/projects-v2/projects.addDeal',
        tag='projects',
        required_params=('deal_id', 'id'),
        optional_params=(),
        description="Add a deal to the project. Doesn't fail if the deal was already added.",
    ),
    'NextgenProjects.addOwner': Endpoint(
        operation_id='NextgenProjects.addOwner',
        method='POST',
        path='/projects-v2/projects.addOwner',
        tag='projects',
        required_params=('id', 'user_id'),
        optional_params=(),
        description="Add a user as owner. Doesn't fail if the user was already added.",
    ),
    'NextgenProjects.addQuotation': Endpoint(
        operation_id='NextgenProjects.addQuotation',
        method='POST',
        path='/projects-v2/projects.addQuotation',
        tag='projects',
        required_params=('id', 'quotation_id'),
        optional_params=(),
        description="Add a quotation to the project. Doesn't fail if the quotation was already added.",
    ),
    'NextgenProjects.assign': Endpoint(
        operation_id='NextgenProjects.assign',
        method='POST',
        path='/projects-v2/projects.assign',
        tag='projects',
        required_params=('assignee', 'id'),
        optional_params=(),
        description='Assign a user or a team to a project.',
    ),
    'NextgenProjects.close': Endpoint(
        operation_id='NextgenProjects.close',
        method='POST',
        path='/projects-v2/projects.close',
        tag='projects',
        required_params=('closing_strategy', 'id'),
        optional_params=(),
        description='Mark a project as closed.',
    ),
    'NextgenProjects.create': Endpoint(
        operation_id='NextgenProjects.create',
        method='POST',
        path='/projects-v2/projects.create',
        tag='projects',
        required_params=('title',),
        optional_params=('assignees', 'billing_method', 'color', 'company_entity_id', 'custom_fields', 'customers', 'deal_ids', 'description', 'end_date', 'external_budget', 'fixed_price', 'initial_amount_billed', 'initial_amount_paid', 'initial_cost', 'initial_price', 'initial_time_tracked', 'internal_budget', 'owner_ids', 'purchase_order_number', 'quotation_ids', 'start_date', 'time_budget'),
        description='Create a new project. Only `title` is required. All the other fields are optional.',
    ),
    'NextgenProjects.delete': Endpoint(
        operation_id='NextgenProjects.delete',
        method='POST',
        path='/projects-v2/projects.delete',
        tag='projects',
        required_params=('delete_strategy', 'id'),
        optional_params=(),
        description='Delete a project.',
    ),
    'NextgenProjects.duplicate': Endpoint(
        operation_id='NextgenProjects.duplicate',
        method='POST',
        path='/projects-v2/projects.duplicate',
        tag='projects',
        required_params=('id', 'title'),
        optional_params=(),
        description='Duplicate a project.',
    ),
    'NextgenProjects.info': Endpoint(
        operation_id='NextgenProjects.info',
        method='POST',
        path='/projects-v2/projects.info',
        tag='projects',
        required_params=('id',),
        optional_params=('includes',),
        description='Returns all the information of a single project.',
    ),
    'NextgenProjects.list': Endpoint(
        operation_id='NextgenProjects.list',
        method='POST',
        path='/projects-v2/projects.list',
        tag='projects',
        required_params=(),
        optional_params=('filter', 'includes', 'page', 'sort'),
        description='Lists all projects that match the optional filters provided.',
    ),
    'NextgenProjects.removeCustomer': Endpoint(
        operation_id='NextgenProjects.removeCustomer',
        method='POST',
        path='/projects-v2/projects.removeCustomer',
        tag='projects',
        required_params=('customer', 'id'),
        optional_params=(),
        description="Remove a customer from the project. Doesn't fail if the customer was not added.",
    ),
    'NextgenProjects.removeDeal': Endpoint(
        operation_id='NextgenProjects.removeDeal',
        method='POST',
        path='/projects-v2/projects.removeDeal',
        tag='projects',
        required_params=('deal_id', 'id'),
        optional_params=(),
        description="Remove a deal from the project. Doesn't fail if the deal was already removed.",
    ),
    'NextgenProjects.removeOwner': Endpoint(
        operation_id='NextgenProjects.removeOwner',
        method='POST',
        path='/projects-v2/projects.removeOwner',
        tag='projects',
        required_params=('id', 'user_id'),
        optional_params=(),
        description="Remove a user as owner. Doesn't fail if the user wasn't linked.",
    ),
    'NextgenProjects.removeQuotation': Endpoint(
        operation_id='NextgenProjects.removeQuotation',
        method='POST',
        path='/projects-v2/projects.removeQuotation',
        tag='projects',
        required_params=('id', 'quotation_id'),
        optional_params=(),
        description="Remove a quotation from the project. Doesn't fail if the quotation was already removed.",
    ),
    'NextgenProjects.reopen': Endpoint(
        operation_id='NextgenProjects.reopen',
        method='POST',
        path='/projects-v2/projects.reopen',
        tag='projects',
        required_params=('id',),
        optional_params=(),
        description='Reopen a closed project.',
    ),
    'NextgenProjects.unassign': Endpoint(
        operation_id='NextgenProjects.unassign',
        method='POST',
        path='/projects-v2/projects.unassign',
        tag='projects',
        required_params=('assignee', 'id'),
        optional_params=(),
        description='Unassign a user or a team from a project.',
    ),
    'NextgenProjects.update': Endpoint(
        operation_id='NextgenProjects.update',
        method='POST',
        path='/projects-v2/projects.update',
        tag='projects',
        required_params=('id',),
        optional_params=('billing_method', 'color', 'company_entity_id', 'custom_fields', 'description', 'end_date', 'external_budget', 'fixed_price', 'internal_budget', 'purchase_order_number', 'start_date', 'time_budget', 'title'),
        description='Update a project. All attributes except for `id` are optional. Providing `null` will clear that value from the project (for properties that are nullable).',
    ),
    'NextgenProjectsTasks.assign': Endpoint(
        operation_id='NextgenProjectsTasks.assign',
        method='POST',
        path='/projects-v2/tasks.assign',
        tag='projects_v2_tasks',
        required_params=('assignee', 'id'),
        optional_params=(),
        description='Assign a user or a team to a task.',
    ),
    'NextgenProjectsTasks.create': Endpoint(
        operation_id='NextgenProjectsTasks.create',
        method='POST',
        path='/projects-v2/tasks.create',
        tag='projects_v2_tasks',
        required_params=('project_id', 'title'),
        optional_params=('assignees', 'billing_method', 'custom_rate', 'description', 'end_date', 'external_budget', 'fixed_price', 'group_id', 'internal_budget', 'start_date', 'task_type_id', 'time_estimated', 'work_type_id'),
        description='Create a task. All properties except for `title` and `project_id` are optional.',
    ),
    'NextgenProjectsTasks.delete': Endpoint(
        operation_id='NextgenProjectsTasks.delete',
        method='POST',
        path='/projects-v2/tasks.delete',
        tag='projects_v2_tasks',
        required_params=('delete_strategy', 'id'),
        optional_params=(),
        description='Delete a task.',
    ),
    'NextgenProjectsTasks.duplicate': Endpoint(
        operation_id='NextgenProjectsTasks.duplicate',
        method='POST',
        path='/projects-v2/tasks.duplicate',
        tag='projects_v2_tasks',
        required_params=('origin_id',),
        optional_params=(),
        description='Duplicate a task, without its time trackings.',
    ),
    'NextgenProjectsTasks.info': Endpoint(
        operation_id='NextgenProjectsTasks.info',
        method='POST',
        path='/projects-v2/tasks.info',
        tag='projects_v2_tasks',
        required_params=('id',),
        optional_params=(),
        description='Returns all the information for one task.',
    ),
    'NextgenProjectsTasks.list': Endpoint(
        operation_id='NextgenProjectsTasks.list',
        method='POST',
        path='/projects-v2/tasks.list',
        tag='projects_v2_tasks',
        required_params=(),
        optional_params=('filter', 'page'),
        description='Lists all the tasks that match the optional filters provided.',
    ),
    'NextgenProjectsTasks.unassign': Endpoint(
        operation_id='NextgenProjectsTasks.unassign',
        method='POST',
        path='/projects-v2/tasks.unassign',
        tag='projects_v2_tasks',
        required_params=('assignee', 'id'),
        optional_params=(),
        description='Unassign a user or a team from a task.',
    ),
    'NextgenProjectsTasks.update': Endpoint(
        operation_id='NextgenProjectsTasks.update',
        method='POST',
        path='/projects-v2/tasks.update',
        tag='projects_v2_tasks',
        required_params=('id',),
        optional_params=('billing_method', 'custom_rate', 'description', 'end_date', 'external_budget', 'fixed_price', 'internal_budget', 'start_date', 'status', 'task_type_id', 'time_estimated', 'title', 'work_type_id'),
        description='Update a task. All attributes except for `id` are optional. Providing `null` will clear that value from the project (for properties that are nullable).',
    ),
    'LegacyProjects.addParticipant': Endpoint(
        operation_id='LegacyProjects.addParticipant',
        method='POST',
        path='/projects.addParticipant',
        tag='legacy_projects',
        required_params=('id', 'participant'),
        optional_params=('role',),
        description='Add a participant to a project.',
    ),
    'LegacyProjects.close': Endpoint(
        operation_id='LegacyProjects.close',
        method='POST',
        path='/projects.close',
        tag='legacy_projects',
        required_params=('id',),
        optional_params=(),
        description='Closes a project, all its phases, and all tasks within each phase (but not meetings).',
    ),
    'LegacyProjects.create': Endpoint(
        operation_id='LegacyProjects.create',
        method='POST',
        path='/projects.create',
        tag='legacy_projects',
        required_params=('milestones', 'participants', 'starts_on', 'title'),
        optional_params=('custom_fields', 'customer', 'description', 'purchase_order_number'),
        description='Create a new project.',
    ),
    'LegacyProjects.delete': Endpoint(
        operation_id='LegacyProjects.delete',
        method='POST',
        path='/projects.delete',
        tag='legacy_projects',
        required_params=('id',),
        optional_params=(),
        description='Delete a project.',
    ),
    'LegacyProjects.info': Endpoint(
        operation_id='LegacyProjects.info',
        method='POST',
        path='/projects.info',
        tag='legacy_projects',
        required_params=('id',),
        optional_params=(),
        description='Get details for a single project.',
    ),
    'LegacyProjects.list': Endpoint(
        operation_id='LegacyProjects.list',
        method='POST',
        path='/projects.list',
        tag='legacy_projects',
        required_params=(),
        optional_params=('filter', 'page', 'sort'),
        description='Get a list of projects.',
    ),
    'LegacyProjects.reopen': Endpoint(
        operation_id='LegacyProjects.reopen',
        method='POST',
        path='/projects.reopen',
        tag='legacy_projects',
        required_params=('id',),
        optional_params=(),
        description='Reopens a project, changing its status to \\"active\\".',
    ),
    'LegacyProjects.update': Endpoint(
        operation_id='LegacyProjects.update',
        method='POST',
        path='/projects.update',
        tag='legacy_projects',
        required_params=('id',),
        optional_params=('budget', 'custom_fields', 'customer', 'description', 'purchase_order_number', 'starts_on', 'status', 'title'),
        description='Update a project.',
    ),
    'LegacyProjects.updateParticipant': Endpoint(
        operation_id='LegacyProjects.updateParticipant',
        method='POST',
        path='/projects.updateParticipant',
        tag='legacy_projects',
        required_params=('id', 'role'),
        optional_params=('participant',),
        description="Update a participant's role for a project.",
    ),
    'quotations.accept': Endpoint(
        operation_id='quotations.accept',
        method='POST',
        path='/quotations.accept',
        tag='quotations',
        required_params=('id',),
        optional_params=(),
        description='Mark a quotation as accepted.',
    ),
    'quotations.create': Endpoint(
        operation_id='quotations.create',
        method='POST',
        path='/quotations.create',
        tag='quotations',
        required_params=('deal_id',),
        optional_params=('currency', 'discounts', 'document_template_id', 'expiry', 'grouped_lines', 'text'),
        description='Create a quotation.',
    ),
    'quotations.delete': Endpoint(
        operation_id='quotations.delete',
        method='POST',
        path='/quotations.delete',
        tag='quotations',
        required_params=('id',),
        optional_params=(),
        description='Delete a quotation.',
    ),
    'quotations.download': Endpoint(
        operation_id='quotations.download',
        method='POST',
        path='/quotations.download',
        tag='quotations',
        required_params=('format', 'id'),
        optional_params=(),
        description='Download a quotation in a specific format.',
    ),
    'quotations.info': Endpoint(
        operation_id='quotations.info',
        method='POST',
        path='/quotations.info',
        tag='quotations',
        required_params=('id',),
        optional_params=(),
        description='Get a quotation.',
    ),
    'quotations.list': Endpoint(
        operation_id='quotations.list',
        method='POST',
        path='/quotations.list',
        tag='quotations',
        required_params=(),
        optional_params=('filter', 'page'),
        description='Get a list of quotations.',
    ),
    'quotations.send': Endpoint(
        operation_id='quotations.send',
        method='POST',
        path='/quotations.send',
        tag='quotations',
        required_params=('content', 'language', 'quotations', 'recipients', 'subject'),
        optional_params=('attachments', 'from'),
        description='Send a quotation.',
    ),
    'quotations.update': Endpoint(
        operation_id='quotations.update',
        method='POST',
        path='/quotations.update',
        tag='quotations',
        required_params=('id',),
        optional_params=('currency', 'discounts', 'document_template_id', 'expiry', 'grouped_lines', 'text'),
        description='Update a quotation.',
    ),
    'receipts.add': Endpoint(
        operation_id='receipts.add',
        method='POST',
        path='/receipts.add',
        tag='receipts',
        required_params=('currency', 'title'),
        optional_params=('company_entity_id', 'document_number', 'file_id', 'receipt_date', 'supplier_id', 'total'),
        description='Adds a receipt.',
    ),
    'receipts.approve': Endpoint(
        operation_id='receipts.approve',
        method='POST',
        path='/receipts.approve',
        tag='receipts',
        required_params=('id',),
        optional_params=(),
        description='Approve a receipt.',
    ),
    'receipts.delete': Endpoint(
        operation_id='receipts.delete',
        method='POST',
        path='/receipts.delete',
        tag='receipts',
        required_params=('id',),
        optional_params=(),
        description='Deletes a receipt.',
    ),
    'receipts.info': Endpoint(
        operation_id='receipts.info',
        method='POST',
        path='/receipts.info',
        tag='receipts',
        required_params=('id',),
        optional_params=(),
        description='Get details for a single receipt.',
    ),
    'receipts.listPayments': Endpoint(
        operation_id='receipts.listPayments',
        method='POST',
        path='/receipts.listPayments',
        tag='receipts',
        required_params=('id',),
        optional_params=(),
        description='List payments for a(n incoming) receipt.',
    ),
    'receipts.markAsPendingReview': Endpoint(
        operation_id='receipts.markAsPendingReview',
        method='POST',
        path='/receipts.markAsPendingReview',
        tag='receipts',
        required_params=('id',),
        optional_params=(),
        description='Mark a receipts as pending review.',
    ),
    'receipts.refuse': Endpoint(
        operation_id='receipts.refuse',
        method='POST',
        path='/receipts.refuse',
        tag='receipts',
        required_params=('id',),
        optional_params=(),
        description='Refuse a receipts.',
    ),
    'receipts.registerPayment': Endpoint(
        operation_id='receipts.registerPayment',
        method='POST',
        path='/receipts.registerPayment',
        tag='receipts',
        required_params=('id', 'paid_at', 'payment'),
        optional_params=('payment_method_id', 'remark'),
        description='Register a payment for a(n incoming) receipt.',
    ),
    'receipts.removePayment': Endpoint(
        operation_id='receipts.removePayment',
        method='POST',
        path='/receipts.removePayment',
        tag='receipts',
        required_params=('id', 'payment_id'),
        optional_params=(),
        description='Remove a payment from a receipt.',
    ),
    'receipts.sendToBookkeeping': Endpoint(
        operation_id='receipts.sendToBookkeeping',
        method='POST',
        path='/receipts.sendToBookkeeping',
        tag='receipts',
        required_params=('id',),
        optional_params=(),
        description='Send a receipt to bookkeeping for processing.',
    ),
    'receipts.update': Endpoint(
        operation_id='receipts.update',
        method='POST',
        path='/receipts.update',
        tag='receipts',
        required_params=('id',),
        optional_params=('company_entity_id', 'currency', 'document_number', 'file_id', 'receipt_date', 'supplier_id', 'title', 'total'),
        description='Updates a receipt.',
    ),
    'receipts.updatePayment': Endpoint(
        operation_id='receipts.updatePayment',
        method='POST',
        path='/receipts.updatePayment',
        tag='receipts',
        required_params=('id', 'payment_id'),
        optional_params=('paid_at', 'payment', 'payment_method_id', 'remark'),
        description='Update a payment for a(n incoming) receipt.',
    ),
    'reservations.create': Endpoint(
        operation_id='reservations.create',
        method='POST',
        path='/reservations.create',
        tag='reservations',
        required_params=('assignee', 'date', 'duration', 'plannable_item_id'),
        optional_params=(),
        description='Create a new reservation.',
    ),
    'reservations.delete': Endpoint(
        operation_id='reservations.delete',
        method='POST',
        path='/reservations.delete',
        tag='reservations',
        required_params=('id',),
        optional_params=(),
        description='Delete a reservation.',
    ),
    'reservations.list': Endpoint(
        operation_id='reservations.list',
        method='POST',
        path='/reservations.list',
        tag='reservations',
        required_params=(),
        optional_params=('filter', 'page'),
        description='Lists all reservations that match the optional filters provided.',
    ),
    'reservations.update': Endpoint(
        operation_id='reservations.update',
        method='POST',
        path='/reservations.update',
        tag='reservations',
        required_params=('id',),
        optional_params=('assignee', 'date', 'duration'),
        description='Update an existing reservation.',
    ),
    'subscriptions.create': Endpoint(
        operation_id='subscriptions.create',
        method='POST',
        path='/subscriptions.create',
        tag='subscriptions',
        required_params=('billing_cycle', 'department_id', 'grouped_lines', 'invoice_generation', 'invoicee', 'payment_term', 'starts_on', 'title'),
        optional_params=('custom_fields', 'deal_id', 'document_template_id', 'ends_on', 'note', 'project_id'),
        description='Create a new subscription.',
    ),
    'subscriptions.deactivate': Endpoint(
        operation_id='subscriptions.deactivate',
        method='POST',
        path='/subscriptions.deactivate',
        tag='subscriptions',
        required_params=('id',),
        optional_params=(),
        description='Deactivate a subscription.',
    ),
    'subscriptions.info': Endpoint(
        operation_id='subscriptions.info',
        method='POST',
        path='/subscriptions.info',
        tag='subscriptions',
        required_params=('id',),
        optional_params=(),
        description='Get details for a single subscription.',
    ),
    'subscriptions.list': Endpoint(
        operation_id='subscriptions.list',
        method='POST',
        path='/subscriptions.list',
        tag='subscriptions',
        required_params=(),
        optional_params=('filter', 'page', 'sort'),
        description='Get a list of subscriptions.',
    ),
    'subscriptions.update': Endpoint(
        operation_id='subscriptions.update',
        method='POST',
        path='/subscriptions.update',
        tag='subscriptions',
        required_params=('id',),
        optional_params=('billing_cycle', 'custom_fields', 'deal_id', 'department_id', 'document_template_id', 'ends_on', 'grouped_lines', 'invoice_generation', 'invoicee', 'note', 'payment_term', 'project_id', 'starts_on', 'title'),
        description='Update a subscription.',
    ),
    'tags.list': Endpoint(
        operation_id='tags.list',
        method='POST',
        path='/tags.list',
        tag='tags',
        required_params=(),
        optional_params=('page', 'sort'),
        description='Get a list of tags.',
    ),
    'tasks.complete': Endpoint(
        operation_id='tasks.complete',
        method='POST',
        path='/tasks.complete',
        tag='tasks',
        required_params=('id',),
        optional_params=(),
        description='Mark a task as complete.',
    ),
    'tasks.create': Endpoint(
        operation_id='tasks.create',
        method='POST',
        path='/tasks.create',
        tag='tasks',
        required_params=('due_on', 'title', 'work_type_id'),
        optional_params=('assignee', 'custom_fields', 'customer', 'deal_id', 'description', 'estimated_duration', 'milestone_id', 'project_id', 'ticket_id'),
        description='Create a new task.',
    ),
    'tasks.delete': Endpoint(
        operation_id='tasks.delete',
        method='POST',
        path='/tasks.delete',
        tag='tasks',
        required_params=('id',),
        optional_params=(),
        description='Delete a task.',
    ),
    'tasks.info': Endpoint(
        operation_id='tasks.info',
        method='POST',
        path='/tasks.info',
        tag='tasks',
        required_params=('id',),
        optional_params=(),
        description='Get information about a task.',
    ),
    'tasks.list': Endpoint(
        operation_id='tasks.list',
        method='POST',
        path='/tasks.list',
        tag='tasks',
        required_params=(),
        optional_params=('filter', 'page', 'sort'),
        description='Get a list of tasks.',
    ),
    'tasks.reopen': Endpoint(
        operation_id='tasks.reopen',
        method='POST',
        path='/tasks.reopen',
        tag='tasks',
        required_params=('id',),
        optional_params=(),
        description='Reopen a task that had been marked as complete.',
    ),
    'tasks.schedule': Endpoint(
        operation_id='tasks.schedule',
        method='POST',
        path='/tasks.schedule',
        tag='tasks',
        required_params=('ends_at', 'id', 'starts_at'),
        optional_params=(),
        description='Schedule a task in your calendar.',
    ),
    'tasks.update': Endpoint(
        operation_id='tasks.update',
        method='POST',
        path='/tasks.update',
        tag='tasks',
        required_params=('id',),
        optional_params=('assignee', 'custom_fields', 'customer', 'deal_id', 'description', 'due_on', 'estimated_duration', 'milestone_id', 'project_id', 'ticket_id', 'title', 'work_type_id'),
        description='Update a task.',
    ),
    'taxRates.list': Endpoint(
        operation_id='taxRates.list',
        method='POST',
        path='/taxRates.list',
        tag='tax_rates',
        required_params=(),
        optional_params=('filter', 'page', 'sort'),
        description='Get a list of available tax rates.',
    ),
    'teams.list': Endpoint(
        operation_id='teams.list',
        method='POST',
        path='/teams.list',
        tag='teams',
        required_params=(),
        optional_params=('filter', 'sort'),
        description='Gets a list of all teams.',
    ),
    'ticketStatus.list': Endpoint(
        operation_id='ticketStatus.list',
        method='POST',
        path='/ticketStatus.list',
        tag='ticket_status',
        required_params=(),
        optional_params=('filter',),
        description='Get a list of ticket statuses.',
    ),
    'tickets.addInternalMessage': Endpoint(
        operation_id='tickets.addInternalMessage',
        method='POST',
        path='/tickets.addInternalMessage',
        tag='tickets',
        required_params=('body', 'id'),
        optional_params=('attachments', 'ticket_status_id'),
        description='Adds an internal message to a ticket.',
    ),
    'tickets.addReply': Endpoint(
        operation_id='tickets.addReply',
        method='POST',
        path='/tickets.addReply',
        tag='tickets',
        required_params=('body', 'id'),
        optional_params=('attachments', 'ticket_status_id'),
        description='Adds a message to a ticket.',
    ),
    'tickets.create': Endpoint(
        operation_id='tickets.create',
        method='POST',
        path='/tickets.create',
        tag='tickets',
        required_params=('customer', 'subject', 'ticket_status_id'),
        optional_params=('assignee', 'custom_fields', 'description', 'initial_reply', 'milestone_id', 'participant'),
        description='Create a ticket.',
    ),
    'tickets.getMessage': Endpoint(
        operation_id='tickets.getMessage',
        method='POST',
        path='/tickets.getMessage',
        tag='tickets',
        required_params=(),
        optional_params=('message_id',),
        description='Gets the ticket message.',
    ),
    'tickets.importMessage': Endpoint(
        operation_id='tickets.importMessage',
        method='POST',
        path='/tickets.importMessage',
        tag='tickets',
        required_params=('body', 'id', 'sent_at', 'sent_by'),
        optional_params=('attachments',),
        description='Imports an existing message to a ticket.',
    ),
    'tickets.info': Endpoint(
        operation_id='tickets.info',
        method='POST',
        path='/tickets.info',
        tag='tickets',
        required_params=('id',),
        optional_params=(),
        description='Get details for a single ticket.',
    ),
    'tickets.list': Endpoint(
        operation_id='tickets.list',
        method='POST',
        path='/tickets.list',
        tag='tickets',
        required_params=(),
        optional_params=('filter', 'page'),
        description='Get a list of tickets.',
    ),
    'tickets.listMessages': Endpoint(
        operation_id='tickets.listMessages',
        method='POST',
        path='/tickets.listMessages',
        tag='tickets',
        required_params=(),
        optional_params=('filter', 'id', 'page'),
        description='Lists messages of a ticket.',
    ),
    'tickets.update': Endpoint(
        operation_id='tickets.update',
        method='POST',
        path='/tickets.update',
        tag='tickets',
        required_params=('id',),
        optional_params=('assignee', 'custom_fields', 'customer', 'description', 'milestone_id', 'participant', 'subject', 'ticket_status_id'),
        description='Update a ticket.',
    ),
    'timeTracking.add': Endpoint(
        operation_id='timeTracking.add',
        method='POST',
        path='/timeTracking.add',
        tag='time_tracking',
        required_params=(),
        optional_params=('description', 'invoiceable', 'subject', 'user_id', 'work_type_id'),
        description='Add tracked time.',
    ),
    'timeTracking.delete': Endpoint(
        operation_id='timeTracking.delete',
        method='POST',
        path='/timeTracking.delete',
        tag='time_tracking',
        required_params=('id',),
        optional_params=(),
        description='Delete a tracked time.',
    ),
    'timeTracking.info': Endpoint(
        operation_id='timeTracking.info',
        method='POST',
        path='/timeTracking.info',
        tag='time_tracking',
        required_params=('id',),
        optional_params=('includes',),
        description='Get information about tracked time.',
    ),
    'timeTracking.list': Endpoint(
        operation_id='timeTracking.list',
        method='POST',
        path='/timeTracking.list',
        tag='time_tracking',
        required_params=(),
        optional_params=('filter', 'includes', 'page', 'sort'),
        description='Get a list of tracked time.',
    ),
    'timeTracking.resume': Endpoint(
        operation_id='timeTracking.resume',
        method='POST',
        path='/timeTracking.resume',
        tag='time_tracking',
        required_params=('id',),
        optional_params=('started_at',),
        description='Start a new timer based on previously tracked time.',
    ),
    'timeTracking.update': Endpoint(
        operation_id='timeTracking.update',
        method='POST',
        path='/timeTracking.update',
        tag='time_tracking',
        required_params=('duration', 'id'),
        optional_params=('description', 'invoiceable', 'subject', 'work_type_id'),
        description='Update tracked time.',
    ),
    'timers.current': Endpoint(
        operation_id='timers.current',
        method='POST',
        path='/timers.current',
        tag='timers',
        required_params=(),
        optional_params=(),
        description='Get the current running timer.',
    ),
    'timers.start': Endpoint(
        operation_id='timers.start',
        method='POST',
        path='/timers.start',
        tag='timers',
        required_params=(),
        optional_params=('description', 'invoiceable', 'started_at', 'subject', 'work_type_id'),
        description='Start a new timer.',
    ),
    'timers.stop': Endpoint(
        operation_id='timers.stop',
        method='POST',
        path='/timers.stop',
        tag='timers',
        required_params=(),
        optional_params=(),
        description='Stop the current timer. This will add a new time tracking in the background.',
    ),
    'timers.update': Endpoint(
        operation_id='timers.update',
        method='POST',
        path='/timers.update',
        tag='timers',
        required_params=(),
        optional_params=('description', 'invoiceable', 'started_at', 'subject', 'work_type_id'),
        description='Update the current timer. Only possible if there is a timer running.',
    ),
    'unitsOfMeasure.list': Endpoint(
        operation_id='unitsOfMeasure.list',
        method='POST',
        path='/unitsOfMeasure.list',
        tag='units_of_measure',
        required_params=(),
        optional_params=(),
        description='Get a list of units of measure.',
    ),
    'userAvailability.daily': Endpoint(
        operation_id='userAvailability.daily',
        method='POST',
        path='/userAvailability.daily',
        tag='user_availability',
        required_params=('period',),
        optional_params=('filter', 'page'),
        description='Returns the daily availability for all users.',
    ),
    'userAvailability.total': Endpoint(
        operation_id='userAvailability.total',
        method='POST',
        path='/userAvailability.total',
        tag='user_availability',
        required_params=('period',),
        optional_params=('filter', 'page'),
        description='Returns the total availability for all users.',
    ),
    'users.getWeekSchedule': Endpoint(
        operation_id='users.getWeekSchedule',
        method='POST',
        path='/users.getWeekSchedule',
        tag='users',
        required_params=('id',),
        optional_params=(),
        description='Returns information about week schedule of a user. Only available with the *Weekly working schedule* feature.',
    ),
    'users.info': Endpoint(
        operation_id='users.info',
        method='POST',
        path='/users.info',
        tag='users',
        required_params=('id',),
        optional_params=('includes',),
        description='Get details for a single user.',
    ),
    'users.list': Endpoint(
        operation_id='users.list',
        method='POST',
        path='/users.list',
        tag='users',
        required_params=(),
        optional_params=('filter', 'page', 'sort'),
        description='Get a list of all users.',
    ),
    'users.listDaysOff': Endpoint(
        operation_id='users.listDaysOff',
        method='POST',
        path='/users.listDaysOff',
        tag='users',
        required_params=('id',),
        optional_params=('filter', 'page'),
        description='Returns information about days off of a given user.',
    ),
    'users.me': Endpoint(
        operation_id='users.me',
        method='POST',
        path='/users.me',
        tag='users',
        required_params=(),
        optional_params=(),
        description='Get the current authenticated user.',
    ),
    'webhooks.list': Endpoint(
        operation_id='webhooks.list',
        method='POST',
        path='/webhooks.list',
        tag='webhooks',
        required_params=(),
        optional_params=(),
        description='List registered webhooks ordered by URL.',
    ),
    'webhooks.register': Endpoint(
        operation_id='webhooks.register',
        method='POST',
        path='/webhooks.register',
        tag='webhooks',
        required_params=('types', 'url'),
        optional_params=(),
        description='Register a new webhook.',
    ),
    'webhooks.unregister': Endpoint(
        operation_id='webhooks.unregister',
        method='POST',
        path='/webhooks.unregister',
        tag='webhooks',
        required_params=('types', 'url'),
        optional_params=(),
        description='Unregister a webhook.',
    ),
    'withholdingTaxRates.list': Endpoint(
        operation_id='withholdingTaxRates.list',
        method='POST',
        path='/withholdingTaxRates.list',
        tag='withholding_tax_rates',
        required_params=(),
        optional_params=('filter',),
        description='Get a list of available withholding tax rates.',
    ),
    'workTypes.list': Endpoint(
        operation_id='workTypes.list',
        method='POST',
        path='/workTypes.list',
        tag='work_types',
        required_params=(),
        optional_params=('filter', 'page', 'sort'),
        description='Get a list of all work types, sorted alphabetically (on their name).',
    ),
}
# fmt: on
